name: financial-mesh
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - plotly
  - jupyter
  - ipykernel
  - black
  - flake8
  - mypy
  - pytest
  - pytest-cov
  - pytest-mock
  - pre-commit
  - opencv
  - pillow
  - flask
  - flask-cors
  - requests
  - websockets
  - h5py
  - joblib
  - tqdm
  - pyyaml
  - python-dotenv
  - rich
  - click
  - pip
  - pip:
    - reportlab==4.1.0
    - pdfplumber==0.11.7
    - PyPDF2==3.0.1
    - pypdfium2==4.30.1
    - pdfminer.six==20250506
    - pdf2image==1.17.0
    - pymupdf==1.24.4
    - camelot-py[cv]==0.11.0
    - tabula-py==2.9.0
    - pytesseract==0.3.10
    - easyocr==1.7.0
    - doctr==1.9.0
    - transformers[torch]==4.53.2
    - tokenizers==0.21.2
    - layoutparser[ocr]==0.3.4
    - layoutparser[effdet]==0.3.4
    - scikit-image==0.22.0
    - docker==7.0.0
    - yfinance==0.2.65
    - numpy-financial==1.0.0
    - dash==3.1.1
    - dash-bootstrap-components==2.0.3
    - spacy==3.8.7
    - en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl#sha256=1932429db727d4bff3deed6b34cfc05df17794f4a52eeb26cf8928f7c1a0fb85
    - networkx==3.5
    - beautifulsoup4==4.13.4
    - retrying==1.4.0
    - multitasking==0.0.11
    - peewee==3.18.2
    - psutil==7.0.0
    - sympy==1.14.0
    - mpmath==1.3.0
    - coverage==7.9.2
    - mypy-extensions==1.1.0
    - typing-extensions==4.14.1
    - typing-inspection==0.4.1
    - fsspec==2025.7.0
    - cloudpathlib==0.21.1
    - smart_open==7.3.0.post1
    - httpx==0.28.1
    - httpcore==1.0.9
    - curl_cffi==0.12.0
    - pydantic==2.11.7
    - pydantic_core==2.33.2
    - annotated-types==0.7.0
    - frozendict==2.4.6
    - protobuf==6.31.1
    - safetensors==0.5.3
    - jinja2==3.1.6
    - markupsafe==3.0.2
    - werkzeug==3.1.3
    - itsdangerous==2.2.0
    - blinker==1.9.0
    - anyio==4.9.0
    - sniffio==1.3.1
    - nest-asyncio==1.6.0
    - regex==2024.11.6
    - markdown-it-py==3.0.0
    - mdurl==0.1.2
    - thinc==8.3.6
    - catalogue==2.0.10
    - confection==0.1.5
    - wasabi==1.1.3
    - srsly==2.5.1
    - preshed==3.0.10
    - murmurhash==1.0.13
    - cymem==2.0.11
    - blis==1.3.0
    - spacy-legacy==3.0.12
    - spacy-loggers==1.0.5
    - weasel==0.4.1
    - typer==0.16.0
    - pathspec==0.12.1
    - pycodestyle==2.14.0
    - pyflakes==3.4.0
    - mccabe==0.7.0
    - iniconfig==2.1.0
    - pluggy==1.6.0
    - pyparsing==3.2.3
    - cycler==0.12.1
    - kiwisolver==1.4.8
    - fonttools==4.59.0
    - contourpy==1.3.2
    - jiter==0.10.0
    - narwhals==1.47.0
    - threadpoolctl==3.6.0
    - platformdirs==4.3.8
    - packaging==25.0
    - six==1.17.0
    - zipp==3.23.0
    - importlib_metadata==8.7.0
    - setuptools==80.9.0
    - shellingham==1.5.4
    - email_validator==2.2.0
    - idna==3.10
    - charset-normalizer==3.4.2
    - urllib3==2.5.0
    - certifi==2025.7.14
    - cffi==1.17.1
    - pycparser==2.22
    - cryptography==45.0.5
    - distro==1.9.0
    - dnspython==2.7.0
    - filelock==3.18.0
    - h11==0.16.0
    - hf-xet==1.1.5
    - huggingface-hub==0.33.4
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - tzdata==2025.2
    - soupsieve==2.7
    - langcodes==3.5.0
    - language_data==1.3.0
    - marisa-trie==1.2.1
    - pygments==2.19.2
    - wrapt==1.17.2
