name: CI

on:
  push:
    branches: [ main, develop, dev/agent-setup ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=79 --statistics

    - name: Test with pytest
      run: |
        pip install pytest
        pytest --maxfail=1 --disable-warnings -q

  test-ubuntu-gpu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo systemctl start docker
        sudo usermod -aG docker $USER

    - name: Build and test Docker image
      run: |
        docker build -t fin-advisor-gpu -f Dockerfile.gpu .
        docker run --rm fin-advisor-gpu python -c "import torch; print('CUDA available:', torch.cuda.is_available())"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=79 --statistics

    - name: Test with pytest
      run: |
        pip install pytest
        pytest --maxfail=1 --disable-warnings -q
